spring:
  application:
    name: FestiGo

  datasource:
    url: jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:5432/postgres
    username: postgres.yupipxqszgjkhflrbyib
    password: "1@mh@r$h05_$up@"

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
    show-sql: true
    open-in-view: false

  thymeleaf:
    check-template-location: false

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

cloudinary:
  cloud-name: dzdcga455
  api-key: "188111427755811"
  api-secret:
    wspnr0RJOax4NHQGn6dN8ykpUqc

    # $env:JAVA_TOOL_OPTIONS='-Duser.timezone=UTC'; .\mvnw.cmd

app:
  # Public domain for the running application (used for CORS and generated links)
  domain: https://festigo-production-f9c6.up.railway.app
